### ISSUE TITLE
Сохранение позиции проигрывателя в аккаунте

### ISSUE THREAD

**Issue by npats2007** [max-frai/book-audio#22]
Сохранение позиции проигрывателя в аккаунте для продолжения прослушивания на других устройствах(смартфон, планшет, компьютер на работе).

**Comment by max-frai** [comment]
Скоро будет. Если авторизируетесь на всех устройствах, автоматически будет подтягиваться. Как доделаю, закрою и вы получите оповещение, спасибо.

**Comment by max-frai** [comment]
Готово.

**Comment by npats2007** [comment]
Спасибо.
