### ISSUE TITLE
Автопроигрывание в Safari не работает

### ISSUE THREAD

**Issue by artemyerofieievsc** [max-frai/book-audio#23]
Автоматическое переключение треков не работает в Safari Version 9.1.2 (11601.7.7). 
В Сhrome работает ок.

Трек переключается на следующий, но не стартует.

**Comment by PFight** [comment]
С мобильного устройства воспроизводите?

**Comment by max-frai** [comment]
Скорее всего у вас мобильное устройство. На android & ios стоит защита, чтобы приложения не могли съесть траффик. Переключить трек можно только после действия пользователя (например, касания пальцем)
