### ISSUE TITLE
При авторизации не входит в карточку.

### ISSUE THREAD

**Issue by npats2007** [max-frai/book-audio#24]
При авторизации не входит в карточку, не авторизованным входит. (chrom-компьютер, safari-iPad).
Авторизация в ВК.

**Comment by max-frai** [comment]
Можете показать вывод консоли разработчика, пожалуйста?
Если не разбираетесь, напишите мне на ockonal@gmail.com,  буду признателен.

**Comment by max-frai** [comment]
починил
