### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by qwertyhansindar** [max-frai/book-audio#29]
После прохождения авторизации, перенаправляет на главную, но авторизации нет( отсутствуют избранное, прослушанное и т.д.
![gif](https://cloud.githubusercontent.com/assets/24483457/25785580/0ffadb16-338d-11e7-9351-1eded912d5b5.gif)
)

**Comment by qwertyhansindar** [comment]
Я так понимаю нет желания выкладывать код в общий доступ, для того чтоб сообщество помогало исправлять ошибки?

**Comment by fotonmoton** [comment]
Я так понимаю #32 баг связан с этим. Поддерживаю OP, если не в опен сорс выкладывать, то дать доступ небольшой группе для тестирования. Сервис очень приятный, не хотелось бы чтобы работа пропадала.

**Comment by max-frai** [comment]
Починил
