### ISSUE TITLE
При создании аккаунта пишет "неверный логин или пароль"

### ISSUE THREAD

**Issue by fotonmoton** [max-frai/book-audio#32]
При регистрации почти всегда пишет "неверный логин или пароль" и все равно регистрирует и перенаправляет на главную страницую
![screenshot_2017-08-18_00-40-39](https://user-images.githubusercontent.com/7763084/29435043-1578ff3e-83ae-11e7-8a84-ce5e26a3482b.png)
![screenshot_2017-08-18_00-41-19](https://user-images.githubusercontent.com/7763084/29435042-157669c2-83ae-11e7-9a4d-cb7ae8b2808f.png)

**Comment by max-frai** [comment]
Спасибо, как раз сейчас бекенд переписываю :) Все будет хорошо ;)

**Comment by fotonmoton** [comment]
@max-frai если нужна помощь - пиши

**Comment by max-frai** [comment]
Починил
