### ISSUE TITLE
UX: сворачивание карточки по щелку на заголовке

### ISSUE THREAD

**Issue by PFight** [max-frai/book-audio#6]
Сейчас единственный способ свернуть карточку - нажать Esc. Это не очень удобно и не интуитивно. Необходимо сделать заголовок карточки кликабельным, так чтобы щелчек по нему сворачивал карточку.

**Comment by max-frai** [comment]
Сделал отдельную иконку в конце заголовка. Раньше весь заголовок был кликабельным, но это мешает скопировать полное название книги (неудобно).

**Comment by PFight** [comment]
Годно.
