### ISSUE TITLE
Слетела favicon

### ISSUE THREAD

**Issue by PFight** [max-frai/book-audio#8]
Слетела favicon. 
![image](https://cloud.githubusercontent.com/assets/198847/21168782/e1b73a60-c1c7-11e6-9757-2593d2751fab.png)

fav2.png недоступен

    <link rel="shortcut icon" href="fav2.png" type="image/x-icon">

**Comment by max-frai** [comment]
Перепроверь, у меня все хорошо

**Comment by PFight** [comment]
Да, сейчас работает.
